spring.application.name=cross-border-pay

signature.url=https://ops-bk.mifos.sandbox.govstack.global/api/v1/util/x-signature
batchtransactions.url=https://bulk-processor.mifos.sandbox.govstack.global/batchtransactions
signature.tenant=greenbank
signature.correlation-id=61ed1793-8150-439e-8ade-d09c633fe823
signature.private-key=